image:
  file: .gitpod.Dockerfile

tasks:
  - name: start mongodb
    command: |
      # For some reason server build fails when mongod is running
      # thus wait until its done.
      gp sync-await server-build
      mongod

  - name: server app
    init: |
      cd /workspace/CodeStats/server-reactive && ./gradlew build
      gp sync-done server-build
    command: |
      cd /workspace/CodeStats/server-reactive &&./gradlew bootRun

  - name: build android
    init: |
      echo sdk.dir=/usr/local/bin/android-sdk > /workspace/CodeStats/mobile/local.properties
      cd /workspace/CodeStats/mobile && ./gradlew build
      

jetbrains:
  intellij:
    vmoptions: "-Xmx4g"
    prebuilds:
      version: stable

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
