image:
  file: .gitpod.Dockerfile

tasks:
  - name: server
    init: cd /workspace/CodeStats/server-reactive && ./gradlew build
    command: cd /workspace/CodeStats/server-reactive &&./gradlew bootRun

vscode:
  extensions:
    - vscjava.vscode-java-pack
